### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by JacobGood1** [emdonahue/SmallKanren#5]
This repo states that the dependencies can be found on the github page:
![image](https://github.com/emdonahue/SmallKanren/assets/3663756/0d340e78-5fea-4e83-a521-8d844b7270e6)
I was not able to locate them, where are they?

**Comment by emdonahue** [comment]
Hello,

The dependencies are all other repositories on my github profile. In
particular, I believe these are all the dependencies:

- https://github.com/emdonahue/Cons
- https://github.com/emdonahue/Contracts
- https://github.com/emdonahue/ABBench
- https://github.com/emdonahue/FunctionalDataStructures

I will make a note to update the README to try to make that clearer.

Thanks,
Evan

**Comment by JacobGood1** [comment]
Thanks so much for the prompt response! I will close this now.
